### ISSUE TITLE
Remove user_session_id from results by default

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-InterviewStats#18]
@BryceStevenWilley looks like there's probably a reason you're capturing this (related to grouping the results?) but it seems like it defeats anonymization. Open to learning more

**Comment by BryceStevenWilley** [comment]
Thanks! TBH, I have no idea why that's there. Happy to remove: https://github.com/SuffolkLITLab/docassemble-InterviewStats/pull/22
