### ISSUE TITLE
ExcelWriter doesn't take an options argument

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-InterviewStats#24]
```
File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9835, in exec_with_trap     exec(the_question.compute, the_dict)   File "<code block>", line 11, in <module> TypeError: ExcelWriter.__new__() got an unexpected keyword argument 'options' 
```

https://github.com/SuffolkLITLab/docassemble-InterviewStats/blame/c42376b1cdb7f05a4a89c76c06c68dd4edf5c016/docassemble/InterviewStats/data/questions/subscribe.yml#L88

**Comment by BryceStevenWilley** [comment]
Gotcha, we have that code copy pasted in this repo, but that does look like the correct fix.

**Comment by BryceStevenWilley** [comment]
That would be fair. That [new argument and other deprecation was made in pandas 1.3.0](https://pandas.pydata.org/pandas-docs/version/1.3/reference/api/pandas.ExcelWriter.html), and [Docassemble has used pandas > 1.3.0 since April 2022](https://github.com/jhpyle/docassemble/blame/9f86ce8f3903c97b076d4e547beb3f2e6c61cecf/docassemble_base/setup.py#L145C6-L145C12). Try except isn't too bad though.

**Comment by nonprofittechy** [comment]
A year to upgrade is fine, I take back my suggestion
