### ISSUE TITLE
Make sure we can handle generating statistics with millions of rows

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-InterviewStats#9]

**Comment by BryceStevenWilley** [comment]
Is this just general scaling issues, or any specific pain points that stand out?

**Comment by nonprofittechy** [comment]
General scaling questions. I don't think we'll exceed millions ever and I want to see if we are likely to ever need background processing.

**Comment by BryceStevenWilley** [comment]
Took a quick look at this while I was thinking about it, and started making some quick changes in https://github.com/SuffolkLITLab/docassemble-InterviewStats/commit/3dd43202fe16517a1ef4ac545613eb4384438559. However, to make significant progress, we'll need to:
* actually see what would make a difference, which needs a DA server with millions of rows that isn't prod, lol. I'll look into doing that soon.
* rethink the interview flow and what sort of statistics we show on the intro screen. Background processing might be needed for exporting all of the data to a spreadsheet, but it shouldn't be for displaying slices of the data, as long as we're smart about our SQL usage. Won't try to over engineer here, but at the least pushing off anything that isn't a summary stat to another screen would be doable and make for much better 2nd page performance.

**Comment by nonprofittechy** [comment]
Maybe we can make a mirror of prod? I can get the postgres dump to you if you want. Right now prod struggles to display the stats for the CDC moratorium. I was trying to pull that one as an example but it didn't work.

**Comment by BryceStevenWilley** [comment]
Haha, that's why I was taking another look at this, I remember running into trouble last month with it. A prod-copy would be helpful, but seems really risky privacy-wise. I was just thinking an interview that calls `store_variables_snapshot` a million times with fake / random data and to let it run locally for however long that takes (it should only take about an hour max?) The effort part would be making the data similar to what's stored in the CDC moratorium.

**Comment by nonprofittechy** [comment]
That makes sense, and would have additional uses for future stress tests.

**Comment by nonprofittechy** [comment]
I added some Pandas stuff to the `help` area which might be to blame for at least some of the speed issues

**Comment by BryceStevenWilley** [comment]
I took out that help part, and we are extremely snappy on 47k rows now! Scaling up to see how much we can handle before timing out again.

Thanks for the tip @nonprofittechy, you saved me at least of day of deep diving.
